services:
  deep-research:
    container_name: deep-research
    build: .
    env_file:
      - .env.local
    ports:
      - "3051:3051"
    # Don't mount volumes - it overwrites the container's node_modules with macOS versions
    # volumes:
    #   -  ./:/app/
    tty: true
    stdin_open: true
